import { useEffect, useState } from "react";
import { fetchToday, fetchBriefing, askAI } from "../api/client";
import { PageHeader, Stat, StatsRowSkeleton, Skeleton, EmptyState, ErrorState } from "../components/ui";
import { useNavigate } from "react-router-dom";

export default function Today() {
  const [data, setData] = useState(null);
  const [brief, setBrief] = useState(null);
  const [briefLoading, setBriefLoading] = useState(true);
  const [error, setError] = useState(null);
  const nav = useNavigate();

  const load = () => {
    setError(null);
    fetchToday().then(setData).catch((e) => setError(e.message));
    setBriefLoading(true);
    fetchBriefing().then(setBrief).catch(() => {}).finally(() => setBriefLoading(false));
  };
  useEffect(load, []);

  if (error) return (<div className="space-y-6"><PageHeader title="Today" subtitle="Your daily supply-chain risk briefing" /><ErrorState message={error} onRetry={load} /></div>);

  return (
    <div className="space-y-6">
      <PageHeader title="Today" subtitle="Your daily supply-chain risk briefing" />

      {/* AI briefing banner - progressive */}
      <div className="card p-5 border-l-4 border-l-brand-600">
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 rounded-lg bg-brand-50 text-brand-600 flex items-center justify-center text-sm font-semibold shrink-0">AI</div>
          <div className="flex-1">
            {briefLoading ? (
              <div className="space-y-2 py-0.5">
                <Skeleton className="h-3.5 w-full max-w-xl" />
                <Skeleton className="h-3.5 w-2/3" />
                <p className="text-xs text-ink-muted mt-1">SupplyLens AI is analyzing live data&hellip;</p>
              </div>
            ) : (
              <div className="fade-in">
                <p className="text-sm font-medium text-ink">{brief?.headline}</p>
                <p className="text-xs text-ink-muted mt-0.5">{brief?.ai ? "Generated by SupplyLens AI from live data" : "Live data summary"}</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* KPIs */}
      {!data ? <StatsRowSkeleton count={3} /> : (
        <div className="grid grid-cols-3 gap-4 fade-in">
          <Stat label="Critical" value={data.critical} sub="action needed < 48 hrs" tone="critical" />
          <Stat label="High" value={data.high} sub="monitor this week" tone="high" />
          <Stat label="Exposure at Risk" value={`$${(data.dollars_at_risk / 1000).toFixed(1)}k`} sub="if unaddressed" tone="brand" />
        </div>
      )}

      <AskAI />

      <div>
        <h2 className="section-title mb-3">Action needed in &lt; 48 hours</h2>
        {!data ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {[0, 1, 2].map((i) => (
              <div key={i} className="card p-5 space-y-3"><Skeleton className="h-5 w-20" /><Skeleton className="h-4 w-40" /><Skeleton className="h-4 w-32" /><Skeleton className="h-9 w-full" /></div>
            ))}
          </div>
        ) : data.cards.length === 0 ? (
          <EmptyState icon="check" title="No critical risks right now" message="Every SKU has a positive buffer. You're in good shape - check back tomorrow." />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 fade-in">
            {data.cards.map((c) => (
              <div key={`${c.sku_id}-${c.site_id}`} className="card p-5 flex flex-col transition-shadow hover:shadow-pop">
                <div className="flex items-center justify-between">
                  <span className="chip chip-critical"><span className="chip-dot" />CRITICAL</span>
                  <span className="text-xs text-ink-muted font-mono">{c.site_id}</span>
                </div>
                <div className="mt-3 font-semibold text-ink">{c.sku_name}</div>
                <div className="text-sm text-ink-soft mt-1">Buffer <span className="font-mono text-[#b42318]">{c.buffer_days}d</span> &middot; <span className="font-mono">${c.dollars_at_risk.toLocaleString()}</span> at risk</div>
                <button onClick={() => nav(`/decision/${c.sku_id}/${c.site_id}`)} className="btn-primary mt-4 w-full">Resolve &rarr;</button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

const SUGGESTED = [
  "What's our biggest stockout risk right now?",
  "Which supplier should I be most concerned about?",
  "What should I prioritize this week?",
];

function AskAI() {
  const [q, setQ] = useState("");
  const [ans, setAns] = useState(null);
  const [busy, setBusy] = useState(false);

  const run = async (question) => {
    const text = question || q.trim();
    if (!text || busy) return;
    setBusy(true); setAns(null); setQ(text);
    try { const r = await askAI(text); setAns(r.answer); }
    catch { setAns("Couldn't reach the AI service."); }
    finally { setBusy(false); }
  };

  return (
    <div className="card p-5">
      <h2 className="section-title mb-3">Ask SupplyLens AI</h2>
      <div className="flex gap-2">
        <input className="input flex-1" value={q} onChange={(e) => setQ(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && run()} placeholder="Ask anything about risk, suppliers, or what to do next..." />
        <button className="btn-primary" onClick={() => run()} disabled={busy || !q.trim()}>{busy ? "Thinking..." : "Ask"}</button>
      </div>
      <div className="flex flex-wrap gap-2 mt-3">
        {SUGGESTED.map((s) => (
          <button key={s} onClick={() => run(s)} className="text-xs text-ink-soft bg-surface-sunken border border-surface-border rounded-full px-3 py-1 hover:border-brand-500 hover:text-ink transition-colors">{s}</button>
        ))}
      </div>
      {busy && (
        <div className="mt-4 space-y-2 border-t border-surface-border pt-3">
          <Skeleton className="h-3.5 w-full" /><Skeleton className="h-3.5 w-5/6" /><Skeleton className="h-3.5 w-2/3" />
        </div>
      )}
      {ans && !busy && <div className="mt-4 text-sm text-ink leading-relaxed border-t border-surface-border pt-3 whitespace-pre-wrap fade-in">{ans}</div>}
    </div>
  );
}
